### ISSUE TITLE
test set MOSEI

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalDataSDK#10]
Is it correct that the MOSEI test set, we are not yet given the truth labels for either emotion or sentiment? Could you please verify if we are to be developing our system using only test/valid. 

```
Traceback (most recent call last):
  File "early_fusion_lstm.py", line 212, in <module>
    y_test = np.array([emotions[vid][sid] for (vid, sid) in test_set_ids])
KeyError: '286943'
```

**Comment by Justin1904** [comment]
We kept the true labels of the test data intentionally, and they will be publicly available once the workshop's official evaluation period is over. So for now you can develop and evaluate your model only on train/valid.

**Comment by rhoposit** [comment]
Yep, I see that now in the workshop description. I had not read it before. thanks!
