### ISSUE TITLE
Missing test ID MOSEI

### ISSUE THREAD

**Issue by blanchardn13** [A2Zadeh/CMU-MultimodalDataSDK#11]
When I load in the test IDs with 
`mosei = Dataloader('http://sorena.multicomp.cs.cmu.edu/downloads/MOSEI')`
`test_ids = mosei.test()`
and print test_ids it appears the first ID is blank/missing. 

I also noticed that 
`valid_ids = mosei.valid()`
returns a set, while the aforementioned test ID's are returned as an array.

**Comment by rhoposit** [comment]
I noticed the first issue too (blank/missing ID). 

For the valid ids, I did not notice that.. my code still works. The data type for valid IDs should not matter (for the purpose of running), since the valid IDs are technically a unique set.

**Comment by A2Zadeh** [comment]
Thank you for raising that issue @blanchardn13. We will look into it more Monday April 2nd and notify you immediately of what might have happened.

**Comment by Justin1904** [comment]
I have checked and removed the blank IDs, it is mistakenly added to the set. Please update the test labels and check if it works, thanks!
