### ISSUE TITLE
grand challenge eval metrics

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalDataSDK#13]
Hi, I'm wondering if we can know in advance which metrics you will use to evaluate the grand challenge submissions. For example, as a simple multilabel classification problem, are you planning to use subset accuracy, per-class accuracy, coverage, etc? And as a regression problem, are you planning to use mean average error, mean square error, etc.. and will it be overall or per-class basis? 

As far as the "winners" of the challenge, will classification and regression be treated separately? For example, is it possible to rank 1st in classification while ranking lower in regression? 

Many thanks!!

**Comment by A2Zadeh** [comment]
Hello Jennifer. Your metrics are auto calculated based on the regression values you output. This has been the convention that we at CMU agreed on to unify the various metrics people use. Otherwise we would have a very hard time evaluating the models for various metrics.

**Comment by rhoposit** [comment]
Thanks Amir! So when we submit the grand challenge predictions, we use the format as it is provided.. Could you verify the format?

For emotion, is it something like: 
`[vid][sid] : {val, val, val, val, val, val}`
or
`[vid][sid] val val val val val val`

Also, do we need to submit both emotion and sentiment to enter the grand challenge? 
And, on the challenge website, it says "Papers that don’t report accuracy on neither test set nor validation set are automatically as workshop papers." Confused.. I thought we are evaluated on regression.. do we pick our own method for evaluating accuracy then?

**Comment by A2Zadeh** [comment]
Yes in fact any format that is easily understandable is accepted! 
For the second point whichever metric you report we will consider for that. If you do regression you are considered for all of the classifications and regression metrics we have. Hope this answers the question.
