### ISSUE TITLE
Do you have a time line regarding including IEMOCAP

### ISSUE THREAD

**Issue by leocnj** [A2Zadeh/CMU-MultimodalDataSDK#14]
Hi Amir,

Thanks for your team's great effort on lowering the complexity of processing multimodal data streams by providing pre-processed MOSI and MOSEI in your SDK. There have been many previous publications on the IEMOCAP data set. Can I ask when do you plan to add the support to this data resource?

**Comment by A2Zadeh** [comment]
Hello Lei,

I believe it should be possible but not in the next 6 months since our priority is with newer datasets such as CMU-MOSEI. If you are interested, you can help us include IEMOCAP in the SDK :)
