### ISSUE TITLE
MOSEI's sentiments labeling

### ISSUE THREAD

**Issue by amirim** [A2Zadeh/CMU-MultimodalDataSDK#15]
Dear Amir,

Many thanks for the kind contribution. I downloaded MOSEI's videos from [this](http://sorena.multicomp.cs.cmu.edu/downloads_raw/MOSEI) link, but the labeling where missing although MOSI's videolabelsentiment.csv file was in the same dowloaded library, can you update the labels file/directory accordingly?

**Comment by A2Zadeh** [comment]
Hello @amirim. The labels are part of the processed version of the dataset downloadable through SDK. Let me know if you were not able to find them.
