### ISSUE TITLE
MOSEI no emotion labels

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalDataSDK#16]
Hello, I see that between training and validation (combined) there are 2,675 segments without an emotion label. The target feature vector looks like:
```
[ 0.  0.  0.  0.  0.  0.]
```
Could I confirm this is just part of the prediction task, and not a case of missing labels?

**Comment by A2Zadeh** [comment]
That is correct. The emotion labels are not a one-hot vector but rather an indicator of presence. So if you don't have any 1s it means no emotion was in the segment. If you have anger and sadness, then two labels will be >=1
