### ISSUE TITLE
I can't down the dataset

### ISSUE THREAD

**Issue by Gyaya** [A2Zadeh/CMU-MultimodalDataSDK#2]
I clone the code in [https://github.com/A2Zadeh/CMU-MultimodalDataSDK](url), and run downloader.py , got "connection timeout error".
Then I accessed to the URL [http://sorena.multicomp.cs.cmu.edu/downloads/mosi/full/MOSI.tar.gz](url), but  "Not found error".
How can I handle this problem?
@A2Zadeh @var95 @paulliangpu @Prateek55 @Justin1904

**Comment by Justin1904** [comment]
Sorry but for now our datasets are not available for downloading for maintenance reasons with our server. We've also put a notice about that in the README file. We're working on making the datasets available for download right now. Please check back later!
