### ISSUE TITLE
features extraction

### ISSUE THREAD

**Issue by amirim** [A2Zadeh/CMU-MultimodalDataSDK#20]
Hi,

How can someone creates the features from an input sample by himself for each of the tri-modality?

**Comment by Justin1904** [comment]
Hi, you can find and download the segmented videos of MOSI or MOSEI through the following links http://sorena.multicomp.cs.cmu.edu/downloads_raw/MOSEI
http://sorena.multicomp.cs.cmu.edu/downloads_raw/MOSI

and you can start your own feature extraction.
