### ISSUE TITLE
MOSI SDK features vs TFN paper

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalDataSDK#22]
Are the features used in the TFN paper exactly the same features that are in the MOSI SDK? Are there any changes, when you made the SDK? (apart from the shaping issue that was mentioned already)

**Comment by A2Zadeh** [comment]
Yes, they are exactly the same features but with some pitfalls. The features in the SDK are not normalized (as they shouldn't be since it is an arbitrary thing to do). The features in the TFN paper are normalized based on the max value for each train and test sample. Does that answer your question?

**Comment by rhoposit** [comment]
yes

**Comment by sverma88** [comment]
Hi Amir,

Did you normalised audio, visual, and textual features or just audio and visual features.
Also to reconfirm your normalisation for a single feature vector x is norm(x) = x/max(x), right?

**Comment by A2Zadeh** [comment]
Yes. We did for CMU-MOSI exactly as the code and data here: https://github.com/pliang279/MFN data, trained models and scripts for data loading is there. Please know that TFN paper use cross-validations and not the convention established later in 

> "Multimodal sentiment analysis with word-level fusion and reinforcement learning"

This is not the case for CMU-MOSEI however. We did completely different things for that dataset.
