### ISSUE TITLE
MOSEI covarep data has inconsistent shapes

### ISSUE THREAD

**Issue by ZackHodari** [A2Zadeh/CMU-MultimodalDataSDK#24]
When loading the audio features for MOSEI I have been coming across an issue where a third of the data has dimensionality 35, and two thirds has dimensionality 74.

It is possible to simple ignore a third of the data, but this seems like a very wasteful solution. Is it possible to get this fixed? Or to get any information on what we can do

```
from mmdata import MOSEI
mosei = MOSEI()
covarep = mosei.covarep()
train_ids = mosei.train()
train_set_ids = [(vid, sid) for vid in train_ids for sid in covarep['covarep'][vid].keys() if sid != 0]
shapes = [[feature.shape for (start_time, end_time, feature) in covarep['covarep'][vid][sid]] for (vid, sid) in train_set_ids]

sum([all(s == (74,) for s in shp) for shp in shapes])  # 11250
sum([all(s == (43,) for s in shp) for shp in shapes])  # 5104
```

**Comment by A2Zadeh** [comment]
The consensus to solve the problem of inconsistency has been to remove those data points from training and testing. This is an issue on our side which will be solved in later stages of the SDK. For the challenge all teams are putting aside those data points. We do apologize for this inconvenience.
