### ISSUE TITLE
Issue no 21 still not resolved.

### ISSUE THREAD

**Issue by ragvri** [A2Zadeh/CMU-MultimodalDataSDK#26]
I have been unable to figure out how to resolve [this](https://github.com/A2Zadeh/CMU-MultimodalDataSDK/issues/21) issue. Can I please get the actual code for the case of windows, please.

**Comment by Justin1904** [comment]
According to https://docs.python.org/2/library/os.html#os.makedirs I think you can try using os.mkdirs(dest).

**Comment by ragvri** [comment]
@Justin1904  I will let you know in 24 hours if this worked or not. :)

**Comment by A2Zadeh** [comment]
Hello @ragvri. To solve the issue you have to fix the problem with making directories in Windows. Other than that at the moment we are busy with the ACL grand challenge on MOSEI, but we will issue a new version of SDK in about a month and we will keep this problem in mind.
