### ISSUE TITLE
problem downloading raw MOSEI

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalDataSDK#28]
Hi, I'm having some trouble downloading the raw MOSEI data using the URL that's listed on the github page. I get an error regarding connection timeout. Is there any way I can download this, or even a large tar file? Thanks!

**Comment by Justin1904** [comment]
@rhoposit Hi, sorry for the inconvenience, your not being able to download the dataset is because our server is currently down. We'll try to get it back online as soon as possible. Thanks for pointing that out, we should put up a notice next time our server is down for maintenance.
