### ISSUE TITLE
COVAREP Features Size Inconsistent

### ISSUE THREAD

**Issue by codeislife99** [A2Zadeh/CMU-MultimodalDataSDK#29]
It seems that half of the COVAREP features are of size 74 for every 0.01 second while half of them are of size 43. The default size when I used the COVAREP framework directly was 74. Is there any reason why so many of the features are of size 43? Because they can't be trained together in that case. So it would be a huge loss of training data and inconsistency in test data as well.

**Comment by A2Zadeh** [comment]
We apologize for the inconvenience. Yes, that is a flaw in the feature processing. We are working on solving it by the end of May. So far, the consensus has been to remove those datapoint from train and test folds.
