### ISSUE TITLE
Number of FACET features not equal to number of labels

### ISSUE THREAD

**Issue by codeislife99** [A2Zadeh/CMU-MultimodalDataSDK#30]
The number of clips which have facet features (from facet.pkl) is :
1. Train Set - 16217
2. Validation Set - 1835

However, the number of clips which have labelings(emotions.pkl) is :
1. Train Set - 16459
2. Validation Set - 1891 

Where is this discrepancy taken care of? If I'm wrong on the above statistics let me know

**Comment by Justin1904** [comment]
@codeislife99 Hi, during the preprocessing of the dataset, we found some data points with annotations to have incomplete/corrupt features so we removed them. That's probably why annotations is more than the actual data.

**Comment by A2Zadeh** [comment]
While this does not affect experiments on CMU-MOSEI, we will fix it in the coming month.
