### ISSUE TITLE
OpenFace for MOSEI?

### ISSUE THREAD

**Issue by sauravsahay** [A2Zadeh/CMU-MultimodalDataSDK#32]
Do you have plans to release OpenFace features for MOSEI dataset? FACET is proprietary and is hard to leverage for online extraction and classification usecases.

**Comment by A2Zadeh** [comment]
Yes, we plan to add more descriptors as we build new tools. For now we only have FACET. We can help you run OpenFace and add the features to our library. Let me know if you are interested in that.

**Comment by KuzmaNg** [comment]
Hi, @sauravsahay . I wanna know how you use the features from OpenFace to do the classification task since MOSI dataset has it. Or any references to it? Thanks a lot.
