### ISSUE TITLE
mismatches in pickle and csv

### ISSUE THREAD

**Issue by harryxu-yscz** [A2Zadeh/CMU-MultimodalDataSDK#34]
I went through some pickled `facet` and csv `facet` MOSI datasets and found some mismatches. For instance, in video_id `03bSnISJMiM`, the print out is
```
[(0.0006469400000028713, 0.033980240000002875, array([  2.37000000e+02,   4.80000000e+01,   2.84000000e+02,
         2.84000000e+02,   2.04367995e-01,  -1.63761997e+00,
        -1.07286000e+00,  -1.87205005e+00,  -5.51613986e-01,
        -6.61406994e-01,  -5.19391000e-01,  -8.27340007e-01,
        -2.63262010e+00,   3.37572008e-01,  -2.31455993e-02,
        -3.04023004e+00,   4.22993988e-01,   4.80691995e-03,
         2.13616006e-02,   5.21924999e-03,   3.22589017e-02,
         8.97189975e-02,   2.32198000e-01,   7.77124986e-02,
         3.03334000e-05,   3.22593004e-01,   9.70017985e-02,
         1.71303995e-11,   3.51815999e-01,  -3.24732989e-01,
         2.73748010e-01,  -3.23579013e-01,  -6.12221003e-01,
         1.03067005e+00,  -1.41479003e+00,  -4.24756017e-03,
        -1.55411005e+00,  -1.28462005e+00,   2.49247000e-01,
        -2.36590004e+00,  -1.29449999e+00,   1.99447006e-01,
        -1.62641001e+00,  -4.05709982e+00,   4.46866989e-01,
         5.21866977e-01], dtype=float32)), ...
```
indicating start_time: `0.0006469400000028713`, end_time: `0.033980240000002875`, and `46` numpy features. But in `MOSI/processed/Video/FACET/Full/03bSnISJMiM.FACET_out.csv`, I found start_time: not listed, end_time: `0.0333333`, which are slightly different. And `47` instead of `46` features. Moreover, each of the feature also seems different.

Would you please share how the pickle files are generated and how is it related to the csv file? Thanks in advance!

**Comment by A2Zadeh** [comment]
Thanks for bringing up this issue. We are looking into it at the moment. For generating the pickle files, you will need some extra files which will be released soon with SDK v1.0.0.
