### ISSUE TITLE
Explanation of the feature sets

### ISSUE THREAD

**Issue by tianleimin** [A2Zadeh/CMU-MultimodalDataSDK#35]
Hi there, could you please point to some references that explain what each feature set extracted on the databases are? 
For example, your opensmile audio feature set for the MOSI database appears to contain 1585 features in total. The one I found that is closest to this feature set is the INTERSPEECH 2010 Paralinguistic Challenge feature set. However, this set contains 1582 features, so I'm puzzled by what the 3 extra features are. 
It will be greatly appreciated if you could add some explanations of the feature sets in the readme file. Thanks!

**Comment by A2Zadeh** [comment]
@tianleimin Very good question. The featureset explanation is included in the newest version of the SDK and will be available to download on June 15th.

**Comment by MichaelGrundie** [comment]
I am unable to find details about which OpenSmile feature set was extracted. I've assumed the INTERSPEECH 2010 Paralinguistic Challenge config file was used. Is that correct?

**Comment by A2Zadeh** [comment]
@MichaelGrundie yes that is correct, in the exact same order as the OpenSmile file outputs information. I do apologize for not having updated the SDK for the OpenSmile feature names. I have been a bit busy lately but updating SDK feature names is still a priority for me. The other feature sets for MOSEI have a field in metadata describing what each feature dimension corresponds to.

**Comment by MichaelGrundie** [comment]
@A2Zadeh Thanks for the quick response and info, much appreciated!
