### ISSUE TITLE
code MARN

### ISSUE THREAD

**Issue by Lhemamou** [A2Zadeh/CMU-MultimodalDataSDK#36]
Hi Amir,

when do you think you will be able to release the code for MARN model?

Best regards,

Léo

**Comment by A2Zadeh** [comment]
@Lhemamou We are planning to release the codes hopefully by the end of June. We are working on the newest version of SDK, so once that is out of the way we got right to the codes :). We are planning to release about 5 codes for different papers.

Thank you for checking in.

**Comment by Lhemamou** [comment]
@A2Zadeh  thanks you ! can't wait to read it ;)
