### ISSUE TITLE
Clarification on Mosei Emotion Intensity?

### ISSUE THREAD

**Issue by KuzmaNg** [A2Zadeh/CMU-MultimodalDataSDK#38]
Hi. Here are some questions on Emotion. I check the emotion labels, about 15 different values included(0, 0.5, 0.67, 1.0etc). So how did you divide the intensity score into groups for every emotion class? Are there 4 groups: 0,1,2,3? Any details on solving the data imbalance problem? Thanks a lot.

**Comment by A2Zadeh** [comment]
Hello @KuzmaNg. There are a total of 3 annotators per video, each are asked to score the presence of emotions on a 4-scale (as you mentioned 0,1,2,3). If x is the emotion, 0 is absence of x, 1 is weak x, x and strong x. I would call the CMU-MOSEI data _realistic_ as opposed to _imbalanced_. While the percentage of the extreme emotions may be low, even in the least frequent extreme emotion (fear) we still have 1900 video segments, which should be enough for many deep approaches. The different prior of the emotions can be explicitly modeled by imposing a uniform prior using a weighted loss.

**Comment by KuzmaNg** [comment]
Thank you, @A2Zadeh. Appreciate that.

**Comment by KuzmaNg** [comment]
Hi. More questions. Is the emotion experiment from Paper(dap-liang-paul-pu) conducted under binary classification or a 4-way classification? I am confused because some types of emotion may not have value-3 samples. And how is the weighted accuracy calculated? I have seen the formula from Tong, but not very sure. Also the F-score, is it only calculated for positive example or the average of both positive and negative? Will the next SDK release solve the problem of the inconsistent dimensions of acoustic features? Thanks so much.

**Comment by raymondwmng** [comment]
Thanks for your explanation @A2Zadeh . Further to this, when i look into the Emotion labels, I saw multiple vectors with different / possibly overlapping time interval. Can i ask
1. is each vector the average score from multiple (max 3) annotators synchronous to the same time interval?
2. will there be cases when there are fewer than / more than 3 annotators ?
3. how are different intervals decided ? I saw some interesting intervals like this.
> cmumosei.computational_sequences['Emotion Labels'].data['zwTrXwi54us[1]']['intervals']
array([[ 2.396,  3.396],
     [ 2.396, 10.849],
     [10.388, 10.849]])

I was following your paper http://aclweb.org/anthology/P18-1208 , just want to confirm if I should treat these scores from multiple intervals as independent and averaged them to derive a segment-level score?

**Comment by rosannamilner** [comment]
Hi @A2Zadeh , I have very similar questions on the reference after the resegmentation. As you can see below before the first and second segment (zwTrXwi54us[0] and zwTrXwi54us[1]) contain the same interval ([2.396, 3.396]). However, in the reference they have two different values ( [0.6666667, 0., 0., 0., 0., 0., 0.] and [0., 0.33333334, 0., 0., 0., 0., 0.]). It's obviously not good for the model to train on the same data twice with two different references. 

What is the best way to prevent confusion in this situation? As suggested in the previous comment, should the reference values be averaged to produce a segment-level score? Or take the longer segments only (though these will still contain overlap)?

Thanks for any help!

`
>>> cmumosei.computational_sequences['Emotion Labels'].data['zwTrXwi54us[0]']['intervals']
array([[0.111, 3.396],
       [2.396, 3.396]])
>>> cmumosei.computational_sequences['Emotion Labels'].data['zwTrXwi54us[0]']['features']
array([[0.        , 0.33333334, 0.        , 0.        , 0.        ,        0.        , 0.        ],
       [0.6666667 , 0.        , 0.        , 0.        , 0.        ,        0.        , 0.        ]], dtype=float32)
>>> cmumosei.computational_sequences['Emotion Labels'].data['zwTrXwi54us[1]']['intervals']
array([[ 2.396,  3.396],
       [ 2.396, 10.849],
       [10.388, 10.849]])
>>> cmumosei.computational_sequences['Emotion Labels'].data['zwTrXwi54us[1]']['features']
array([[0.        , 0.33333334, 0.        , 0.        , 0.        ,        0.        , 0.        ],
       [0.6666667 , 0.        , 0.        , 0.        , 0.        ,        0.        , 0.        ],
       [0.6666667 , 0.6666667 , 0.        , 0.        , 0.        ,        0.        , 0.        ]], dtype=float32)
`

**Comment by A2Zadeh** [comment]
Hello @rosannamilner @raymondwmng 

The overlap between segments is artificially created by us. We extend the beginning and the end by I think 0.5 seconds. Therefore you can average or rather just trim 0.5 whenever this happens. We are planning to fix this however, so you don't need to manually fix it.

**Comment by rosannamilner** [comment]
Thanks for the quick response - Ok I see, glad to hear this will be fixed then, thanks again for the help!
