### ISSUE TITLE
Download Link time out

### ISSUE THREAD

**Issue by DraculaAlbert** [A2Zadeh/CMU-MultimodalDataSDK#39]
Hi, I am downloading the MOSEI  from the following link

CMU-MOSEI | http://sorena.multicomp.cs.cmu.edu/downloads_raw/MOSEI

However, it seems I cannot visit the website(time out). Is there something wrong with the site or just something wrong with my machine? 

Thank you!

**Comment by A2Zadeh** [comment]
Hello @DraculaAlbert. We are undergoing a maintenance and a new release period before ACL 2018. Our website will be down till July 15th. We will come back with a much stronger API and more dataset functionalities. Thanks.
