### ISSUE TITLE
load pkl data from file?

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalDataSDK#4]
Hi, I am trying to work with covarep data. It's 18GB. I downloaded it, and it now sits in a folder (as determined by the data script). But when I want to use it, I hit a memory error. I think it is trying to load 18Gb of pkl data into memory. Is that the intended functionality? What are some commands I can use to get around this problem?

**Comment by rhoposit** [comment]
i moved to a larger system, nevermind. but something to consider in the future is that .pkl is not everyone's favorite serialization method ;)

**Comment by Justin1904** [comment]
Sorry for the inconvenience! By the way do you have any suggestions for serialization methods? Indeed reading that much data into memory might be a problem for users. We're open to suggestions :)

**Comment by A2Zadeh** [comment]
Thank you for using the CMU Multimodal Data SDK Jennifer (@rhoposit). Multimodal data is unfortunately often large in size. As mentioned by my student Zhun (@Justin1904) we are open to suggestions on how the community would rather see the data format. We can put it in h5py or other formats. Thank you for your comment and we look forward to hearing from you.

**Comment by A2Zadeh** [comment]
Thanks Jennifer. Which one of these options would you see yourself using? All of them are implementable. We are aware that currently downloading a large file has its issues. That being said storing and loading into RAM is also another issue. We are planning to include a section in the readme on best practices on using the loader.

**Comment by rhoposit** [comment]
Wow thank you! I am not sure yet. Right now my team is using the smaller MOSI data to work on, rather than the MOSEI data. We hope to switch over to MOSEI data shortly, so that we can enter into the ACL challenge. I hope to have a clearer idea in the coming weeks.
