### ISSUE TITLE
covarep data shape

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalDataSDK#5]
I am consistently getting an error that the covarep MOSEI data is not all the same shape. What I did was take your example script for early fusion lstm (combining embeddings and covarep) and removed all references to embeddings (therefore using only audio features). However, 

```
    train_set_audio = np.stack([pad(covarep['covarep'][vid][sid], max_len) for (vid, sid) in train_set_ids if covarep['covarep'][vid][sid]], axis=0)
  File "/home/xxxxxx/.local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 353, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

note that I get a similar error about shape when trying to follow the example script text_lstm.py, replacing embeddings with covarep. Could you confirm that there is no issue with covarep data shape? or suggest how I might fix this problem? Note also this error only happens on MOSEI data, and the MOSI data works just fine. BTW what's the difference between these two?

**Comment by A2Zadeh** [comment]
@rhoposit: We are looking into the details of this issue. It seems that two of our data points seem to have smaller dimensions that the rest of the dataset. We will contact you on how to solve it on your side and we will commit the updated version by the end of weekend.

**Comment by Justin1904** [comment]
Indeed the demo code won't work if directly used on MOSEI. There are a few entries in MOSEI that has different shapes than others. They are either empty (implying for this segment of video clip that modality is missing or the feature extractor doesn't detect anything) or in rare cases they have different shapes. These data points should generally be discarded. I think for MOSEI covarep there're 2 such data points, both in video ID '100499', segment '0' and segment '1'. We'll make this point clear in our future versions of demo or maybe remove such data points completely.

**Comment by rhoposit** [comment]
Thanks so very much for confirming!
