### ISSUE TITLE
Where can I find the access to raw data of MOSEI dataset?

### ISSUE THREAD

**Issue by wtomin** [A2Zadeh/CMU-MultimodalDataSDK#6]
Hi, I notice that in the URLs for the raw files of the dataset that you have provided , there is no URL for MOSEI dataset. Probably it is too big in size.  But I plan to extract some visual features using deep neural network, so it will be more handy if there are original videos or frames of MOSEI. 

Is there any access to the raw file of MOSEI dataset? Thanks.

**Comment by rhoposit** [comment]
I was able to get it by changing the URL, where it specifies "MOSI" in the URL, just change that to "MOSEI". It worked for me.

**Comment by var95** [comment]
Can you please check now? It should be available for download.

Sorry for the delay.
