### ISSUE TITLE
Regarding MOSEI dataset.

### ISSUE THREAD

**Issue by deepanwayx** [A2Zadeh/CMU-MultimodalDataSDK#8]
By using the MOSEI dataloader and emotions.pkl file I got a 6 column numpy array as the target vector. I assume these are the intensities for 6 different kind of emotions. However, it is not clear which column indicates which emotion type. I did a histogram plot and comparing the plot [here,](http://multicomp.cs.cmu.edu/resources/cmu-mosei-dataset/) it seems that 

column1: sadness, column2: disgust, column3: surprise, 
column4: happiness, column5: anger, column6: fear

Can you confirm if this is indeed the case?

Also in the plot [here,](http://multicomp.cs.cmu.edu/resources/cmu-mosei-dataset/) the sentiment intensities has been categorized in 5 classes. The intensities vary from -3 to +5 in the train and valid data. Please specify what intensity boundary levels the classes comprises of?

**Comment by blanchardn13** [comment]
I also noticed the issues with the sentiment bounds.

Sentiment is bound [-3,3] according to http://multicomp.cs.cmu.edu/resources/cmu-mosi-dataset/

There are three videos in the MOSEI dataset where these bounds are violated:
2HP4KedfmSc_5
XDVkhOziCkg_0
sC1NvtirijU_21

There are also three videos where emotion labels range above 3:
2HP4KedfmSc_0
XDVkhOziCkg_0
sC1NvtirijU_21

In total there are four 'suspicious' videos, as two of the videos appear to exceed both sentiment and emotion bounds. I suspect the labels from these four videos need to be rechecked.

**Comment by A2Zadeh** [comment]
Hello. We are currently looking into both the above issues. 

First the emotion column labels will be announced soon, we do apologize for that. During organization of big events sometimes small things get overlooked. 

For the samples, it is also very strange to us why this might have happened. The other data points remain correct and can be used to train models in the meantime. We will be in touch.

**Comment by Justin1904** [comment]
@deepanwayx Hello, the emotions for each of the dimensions are: anger, disgust, fear, happy, sad, surprise. As for the sentiments, they should be in range [-3, +3], and the intervals are just evenly divided. We are aware that a few data points seem to have out-of-bounds annotations, and we'll clip them. So you can also just clip those values beyond [-3, 3].

**Comment by deepanwayx** [comment]
Thanks @Justin1904

**Comment by Justin1904** [comment]
@blanchardn13 We have checked the labels and updated the annotations for a few data points. You can update the labels now (just delete the sentiments and emotions pickle file under your SDK folder and reload them)

**Comment by blanchardn13** [comment]
Sounds good @Justin1904  - thanks so much

**Comment by raymondwmng** [comment]
Hello, i have downloaded the new SDK today and source the raw and label data again
seems that there are now 7 classes instead of 6. (see the example below)
Also the order of the classes to which labels correspond to seem different now.
Can you advise? 

x.computational_sequences['Emotion Labels'].data['DZBpdzrMelA[0]']
{'intervals': array([[ 3.344, 16.666]]), 'features': array([[1.6666666, 0.6666667, 0.       , 0.       , 0.       , 0.       ,
        0.       ]], dtype=float32)}

**Comment by A2Zadeh** [comment]
@raymondwmng Let me look into the issue. I think the first one might actually be sentiment. Yeah I am going to add the functionality to get that information easily. It would be a field in compseq.metadata.

**Comment by A2Zadeh** [comment]
@raymondwmng you can download the data again. It should be fixed for labels. The metadata bit takes longer for me to process.

**Comment by raymondwmng** [comment]
thanks @A2Zadeh !
