### ISSUE TITLE
cannot download & load word embeddings

### ISSUE THREAD

**Issue by papagandalf** [A2Zadeh/CMU-MultimodalDataSDK#9]
Hi,
Following the instructions of the "Fetching Datasets", when I do
```python
>>> mosei_emb = mosei.embeddings() # download & load word embeddings
```
I get the following error:

```
The requested data is not available for http://sorena.multicomp.cs.cmu.edu/downloads/MOSEI dataset.
```

Browsing the contents of http://sorena.multicomp.cs.cmu.edu/downloads/MOSEI/, I saw there is an embedding.pkl (as opposed to embeddings.pkl) file. Is this the one?

**Comment by var95** [comment]
Hi,

Yes that is the one. It has been renamed to embeddings.pkl now. Thank you for catching the typo!
